version: 2.0

jobs:
  "go-1.11":
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/utahta/go-cronowriter
    steps:
      - checkout
      - run: make mod
      - run:
          name: Run tests
          command: make test

  "go-1.12":
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/utahta/go-cronowriter
    steps:
      - checkout
      - run: make mod
      - run:
          name: Run tests
          command: make test

  "go-1.13":
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/utahta/go-cronowriter
    steps:
      - checkout
      - run: make mod
      - run:
          name: Run tests
          command: make test
  "go-1.14":
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/utahta/go-cronowriter
    steps:
      - checkout
      - run: make mod
      - run:
          name: Run tests
          command: make test

workflows:
  version: 2
  build:
    jobs:
      - "go-1.11"
      - "go-1.12"
      - "go-1.13"
      - "go-1.14"
